mv files/[aA]* a/
mv files/[bB]* b/
mv files/[cC]* c/
mv files/[dD]* d/
mv files/[eE]* e/
mv files/[fF]* f/
mv files/[gG]* g/
mv files/[hH]* h/
mv files/[iI]* i/
mv files/[jJ]* j/
mv files/[kK]* k/
mv files/[lL]* l/
mv files/[mM]* m/
mv files/[nN]* n/
mv files/[oO]* o/
mv files/[pP]* p/
mv files/[qQ]* q/
mv files/[rR]* r/
mv files/[sS]* s/
mv files/[tT]* t/
mv files/[uU]* u/
mv files/[vV]* v/
mv files/[wW]* w/
mv files/[xX]* x/
mv files/[yY]* y/
mv files/[zZ]* z/